export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

export enum DEPOSIT {
  NFT = 'nft',
  TOKEN = 'token',
}

export const MOCK_REVEAL_PACK_DATA = [
  {
    owner: '0xeb84064b04005055293dbc411855bac4dd5a078e',
    tokenId: 30971,
    tracking: 1,
    sourceFrom: 'onchain: TomoChain-0x79B8bAED9C2384188Dd7820D76282709024a38e4-30971',
    cardId: 1,
    rarity: 2,
    level: 3,
    mutant: {
      atk: 0,
      hp: 0,
    },
    name: 'Alpha Wolf',
    description: 'The representative power of the Beasts, wolf warriors are steadfast even on their dying breath.',
    type: 1,
    artName: '',
    cardAssets: '',
    backgroundUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/1_r_bg.png',
    charUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/1_r_char.png',
    assetVersion: 1,
    imageUrl: 'https://storagemollectordev.blob.core.windows.net/images/card-1-30971-1-2-3-0-0.png',
    imageGenUrl: 'https://api-dev.mollector.com/api/Images/card-1-30971-1-2-3-0-0.png',
    elite: false,
    originATK: 6,
    originHP: 13,
    ATK: 6,
    HP: 13,
    longRangeAttack: false,
    skills: [
      {
        effect: 'Death Howl',
        trigger: '',
        name: 'Death Howl',
        description: '<b>Give +5/+5</b>  to fellow <b>Beasts</b> when fallen.',
      },
    ],
  },
  {
    owner: '0xeb84064b04005055293dbc411855bac4dd5a078e',
    tokenId: 30972,
    tracking: 1,
    sourceFrom: 'onchain: TomoChain-0x79B8bAED9C2384188Dd7820D76282709024a38e4-30972',
    cardId: 21,
    rarity: 2,
    level: 1,
    mutant: {
      atk: 0,
      hp: 0,
    },
    name: 'Striker',
    description:
      'With the lack of magic or anti-physical powers, the Mechs compensate with brutal mechanical might. Strikers do exactly what they are called.',
    type: 5,
    artName: '',
    cardAssets: '',
    backgroundUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/21_r_bg.png',
    charUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/21_r_char.png',
    assetVersion: 1,
    imageUrl: 'https://storagemollectordev.blob.core.windows.net/images/card-1-30972-21-2-1-0-0.png',
    imageGenUrl: 'https://api-dev.mollector.com/api/Images/card-1-30972-21-2-1-0-0.png',
    elite: false,
    originATK: 4,
    originHP: 11,
    ATK: 4,
    HP: 11,
    longRangeAttack: false,
    skills: [
      {
        effect: 'Cleave Strike',
        trigger: '',
        name: 'Cleave Strike',
        description: 'Deal <b>4</b> damage to a target and 2 adjacent cards left and right.',
      },
    ],
  },
  {
    owner: '0xeb84064b04005055293dbc411855bac4dd5a078e',
    tokenId: 30973,
    tracking: 1,
    sourceFrom: 'onchain: TomoChain-0x79B8bAED9C2384188Dd7820D76282709024a38e4-30973',
    cardId: 45,
    rarity: 2,
    level: 1,
    mutant: {
      atk: 0,
      hp: 0,
    },
    name: 'Soul Eater',
    description:
      "A grotesk copy of the Dragon's Sacred Beacon, only that it doesn't give life, it takes life with the kind of magic that even Dragons can't repel.",
    type: 3,
    artName: '',
    cardAssets: '',
    backgroundUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/45_r_bg.png',
    charUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/45_r_char.png',
    assetVersion: 1,
    imageUrl: 'https://storagemollectordev.blob.core.windows.net/images/card-1-30973-45-2-1-0-0.png',
    imageGenUrl: 'https://api-dev.mollector.com/api/Images/card-1-30973-45-2-1-0-0.png',
    elite: true,
    originATK: 4,
    originHP: 4,
    ATK: 4,
    HP: 4,
    longRangeAttack: false,
    skills: [
      {
        effect: 'Soul steal',
        trigger: '',
        name: 'Soul steal',
        description: 'Imediately destroy <b>1</b> enemy card(s) when defeated.',
      },
    ],
  },
  {
    owner: '0xeb84064b04005055293dbc411855bac4dd5a078e',
    tokenId: 30974,
    tracking: 1,
    sourceFrom: 'onchain: TomoChain-0x79B8bAED9C2384188Dd7820D76282709024a38e4-30974',
    cardId: 4,
    rarity: 2,
    level: 3,
    mutant: {
      atk: 0,
      hp: 0,
    },
    name: 'Abyss Dweller',
    description: 'Secretive creatures of the Abyss who are not fond of violence but very good at preventing death.',
    type: 1,
    artName: '',
    cardAssets: '',
    backgroundUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/4_r_bg.png',
    charUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/4_r_char.png',
    assetVersion: 1,
    imageUrl: 'https://storagemollectordev.blob.core.windows.net/images/card-1-30974-4-2-3-0-0.png',
    imageGenUrl: 'https://api-dev.mollector.com/api/Images/card-1-30974-4-2-3-0-0.png',
    elite: false,
    originATK: 5,
    originHP: 11,
    ATK: 5,
    HP: 11,
    longRangeAttack: false,
    skills: [
      {
        effect: 'Resurrection',
        trigger: '',
        name: 'Resurrection',
        description: 'On attacking, give <b>2</b> friendly <b>Beast(s)</b> Resurrection guarantee.',
      },
    ],
  },
  {
    owner: '0xeb84064b04005055293dbc411855bac4dd5a078e',
    tokenId: 30975,
    tracking: 1,
    sourceFrom: 'onchain: TomoChain-0x79B8bAED9C2384188Dd7820D76282709024a38e4-30975',
    cardId: 29,
    rarity: 2,
    level: 1,
    mutant: {
      atk: 0,
      hp: 0,
    },
    name: 'Rogue ',
    description:
      "The only beings known to frequent the forbidden planets where most wouldn't survive. They have a natural affinity with the most deadly substances found in the universe.",
    type: 6,
    artName: '',
    cardAssets: '',
    backgroundUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/29_r_bg.png',
    charUrl: 'https://storagemollectordev.blob.core.windows.net/hero-assets/29_r_char.png',
    assetVersion: 1,
    imageUrl: 'https://storagemollectordev.blob.core.windows.net/images/card-1-30975-29-2-1-0-0.png',
    imageGenUrl: 'https://api-dev.mollector.com/api/Images/card-1-30975-29-2-1-0-0.png',
    elite: true,
    originATK: 4,
    originHP: 9,
    ATK: 4,
    HP: 9,
    longRangeAttack: false,
    skills: [
      {
        effect: 'Poison Strike',
        trigger: '',
        name: 'Poison Strike',
        description: 'Imediately destroy enemy cards on contact when attacking and defending.',
      },
    ],
  },
]

export const MOCK_PACK_INFO = [
  {
    owner: '0xeB84064b04005055293DbC411855BaC4dd5a078E',
    packType: 7,
    openedAt: 0,
    tokenId: '13',
    network: 'TomoChain',
    sourceFrom: 'onchain: TomoChain-0x788dbEC813Fb26EA560C73D0ECa006071533Ba7f-13',
    cards: null,
  },
]
